#!/usr/local/bin/python
# -*- coding: utf8 -*-

#osm-hell

import cgi, sys, json
import psycopg2
import psycopg2.extras
import db_config

rows=['id','lat','lon','city','street','house','flat','contact','phone','required','info','condition_house','status']
output={}

def getdata():
  getval={}
  getval['_search'] = getvalues.getfirst('_search','')

  where = ' true '
  for name in rows:
    getval[name] = getvalues.getfirst(name,'')
    if (getval[name]<>'' and getval['_search']<>''):
      getval[name]=getval[name]+'%'
      where = where + ' AND '+name+' ILIKE %('+name+')s'

  cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
  cur.execute("""
    SELECT *
    FROM
      hell_data
    WHERE
      """+where+"""
  ;""",getval)
  data = {}
  data['rows']=[]
  for record in cur:
    data['rows'].append(record)
  print json.dumps(data)

def setdata():
  getval={}
  getval['oper'] = getvalues.getfirst('oper','')
  for name in rows:
    if (name=='lat' or name=='lon'):
      getval[name] = float(getvalues.getfirst(name,'0'))
    else:
      getval[name] = getvalues.getfirst(name,'')

  cur = conn.cursor()
  try:
    if ( getval['oper'] == 'add' ):
      cur.execute("""
        INSERT INTO hell_data(city, street, house, flat, contact, phone, required, info, lat, lon, condition_house)
          VALUES (%(city)s, %(street)s, %(house)s, %(flat)s, %(contact)s, %(phone)s, %(required)s, %(info)s, %(lat)s, %(lon)s, %(condition_house)s);
      ;""", getval)
    elif ( getval['oper'] == 'edit' ):
      cur.execute("""
        UPDATE hell_data
           SET city=%(city)s, street=%(street)s, house=%(house)s, flat=%(flat)s, contact=%(contact)s, phone=%(phone)s,
               required=%(required)s, info=%(info)s, lat=%(lat)s, lon=%(lon)s, condition_house=%(condition_house)s
          WHERE id=%(id)s;
      ;""", getval)

    conn.commit()
  except Exception, e:
    output['error'] = str(e)

def getpoint():
  getval={}
  getval['maxlat'] = float(getvalues.getfirst('maxlat','0'))
  getval['maxlon'] = float(getvalues.getfirst('maxlon','0'))
  getval['minlat'] = float(getvalues.getfirst('minlat','0'))
  getval['minlon'] = float(getvalues.getfirst('minlon','0'))
  for k in getval:
    if (getval[k] == 0):
      output['error']=("%(k)s is not null"%{'k':k})
      return

  cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
  cur.execute("""
    SELECT id, city, street, house, flat, contact, phone, required, info,
           lat, lon, condition_house
      FROM hell_data
      WHERE
        lat > %(minlat)s
        and lat < %(maxlat)s
        and lon > %(minlon)s
        and lon < %(maxlon)s
  ;""",getval)
  data = []
  for record in cur:
    data.append(record)
  output['data']=data



#send = "Content-type: text/javascript;" # debug
send = "Content-type: application/json;" # production
send = send + " Charset=Utf-8\nAccess-Control-Allow-Origin: *\nAccess-Control-Request-Headers: X-Requested-With, X-Prototype-Version\nAccess-Control-Request-Method: GET\n"
print send # production

conn = psycopg2.connect(host=db_config.site_host, database=db_config.site_database, user=db_config.site_user, password=db_config.site_password)

getvalues=cgi.FieldStorage()
output['action'] = getvalues.getfirst('action','')
if output['action'] == 'getdata':
  getdata()
elif output['action'] == 'setdata':
  setdata()
elif output['action'] == 'getpoint':
  getpoint()
else:
  output['error']='wrong action'

if (output['action'] <> 'getdata'):
  #if (output['type'] == 'callback'):
  print json.dumps(output)
